In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\Texas\Harris\Property\Raw_Data\us_tx_48201_data_prop_exemption-jurisdictions_bronze_20260501.csv")
df

C:\Users\keisha.sonasaniya\AppData\Local\Temp\ipykernel_24064\2507497185.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\Texas\Harris\Property\Raw_Data\us_tx_48201_data_prop_exemption-jurisdictions_bronze_20260501.csv")

,parcel,exemption_value,rate_2023,arb_status,jurisdiction,rate_2025,rate_2026,rate_2024,year,rate_2022,rate_2020,rate_2021,district,page_save
0,1166790050010,"38,042",NaN,Certified: 08/06/2021,CLEAR CREEK ISD,NaN,NaN,NaN,2021,NaN,1.26590,1.17970,027,1166790050010_2021.html
1,1166790050010,"52,166",NaN,Certified: 08/06/2021,HARRIS COUNTY,NaN,NaN,NaN,2021,NaN,0.39116,0.37693,040,1166790050010_2021.html
2,1166790050010,"52,166",NaN,Certified: 08/06/2021,HARRIS CO FLOOD CNTRL,NaN,NaN,NaN,2021,NaN,0.03142,0.03349,041,1166790050010_2021.html
3,1166790050010,"52,166",NaN,Certified: 08/06/2021,PORT OF HOUSTON AUTHY,NaN,NaN,NaN,2021,NaN,0.00991,0.00872,042,1166790050010_2021.html
4,1166790050010,"52,166",NaN,Certified: 08/06/2021,HARRIS CO HOSP DIST,NaN,NaN,NaN,2021,NaN,0.16671,0.16221,043,1166790050010_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45356821,451750020001,NaN,NaN,Not Certified,PORT OF HOUSTON AUTHY,0.005900,NaN,NaN,2026,NaN,NaN,NaN,042,0451750020001_2026.html
45356822,451750020001,NaN,NaN,Not Certified,HARRIS CO HOSP DIST,0.187610,NaN,NaN,2026,NaN,NaN,NaN,043,0451750020001_2026.html
45356823,451750020001,NaN,NaN,Not Certified,HARRIS CO EDUC DEPT,0.004798,NaN,NaN,2026,NaN,NaN,NaN,044,0451750020001_2026.html
45356824,451750020001,NaN,NaN,Not Certified,CITY OF HOUSTON,0.519190,NaN,NaN,2026,NaN,NaN,NaN,061,0451750020001_2026.html
45356825,451750020001,NaN,NaN,Not Certified,SPRING BRANCH MGT DIST,0.100000,NaN,NaN,2026,NaN,NaN,NaN,793,0451750020001_2026.html

In [3]:
df['parcel'] = df['page_save'].str.split('_').str[0]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45356826 entries, 0 to 45356825
Data columns (total 14 columns):
 #   Column           Dtype
---  ------           -----
 0   parcel           object
 1   exemption_value  object
 2   rate_2023        float64
 3   arb_status       object
 4   jurisdiction     object
 5   rate_2025        float64
 6   rate_2026        float64
 7   rate_2024        float64
 8   year             int64
 9   rate_2022        float64
 10  rate_2020        float64
 11  rate_2021        float64
 12  district         object
 13  page_save        object
dtypes: float64(7), int64(1), object(6)
memory usage: 4.7+ GB

In [5]:
df

,parcel,exemption_value,rate_2023,arb_status,jurisdiction,rate_2025,rate_2026,rate_2024,year,rate_2022,rate_2020,rate_2021,district,page_save
0,1166790050010,"38,042",NaN,Certified: 08/06/2021,CLEAR CREEK ISD,NaN,NaN,NaN,2021,NaN,1.26590,1.17970,027,1166790050010_2021.html
1,1166790050010,"52,166",NaN,Certified: 08/06/2021,HARRIS COUNTY,NaN,NaN,NaN,2021,NaN,0.39116,0.37693,040,1166790050010_2021.html
2,1166790050010,"52,166",NaN,Certified: 08/06/2021,HARRIS CO FLOOD CNTRL,NaN,NaN,NaN,2021,NaN,0.03142,0.03349,041,1166790050010_2021.html
3,1166790050010,"52,166",NaN,Certified: 08/06/2021,PORT OF HOUSTON AUTHY,NaN,NaN,NaN,2021,NaN,0.00991,0.00872,042,1166790050010_2021.html
4,1166790050010,"52,166",NaN,Certified: 08/06/2021,HARRIS CO HOSP DIST,NaN,NaN,NaN,2021,NaN,0.16671,0.16221,043,1166790050010_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45356821,0451750020001,NaN,NaN,Not Certified,PORT OF HOUSTON AUTHY,0.005900,NaN,NaN,2026,NaN,NaN,NaN,042,0451750020001_2026.html
45356822,0451750020001,NaN,NaN,Not Certified,HARRIS CO HOSP DIST,0.187610,NaN,NaN,2026,NaN,NaN,NaN,043,0451750020001_2026.html
45356823,0451750020001,NaN,NaN,Not Certified,HARRIS CO EDUC DEPT,0.004798,NaN,NaN,2026,NaN,NaN,NaN,044,0451750020001_2026.html
45356824,0451750020001,NaN,NaN,Not Certified,CITY OF HOUSTON,0.519190,NaN,NaN,2026,NaN,NaN,NaN,061,0451750020001_2026.html
45356825,0451750020001,NaN,NaN,Not Certified,SPRING BRANCH MGT DIST,0.100000,NaN,NaN,2026,NaN,NaN,NaN,793,0451750020001_2026.html

In [6]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x)

In [7]:
# Define fake null values
fake_nulls = ['', 'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null','NONE']
 

# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]
   
    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)
        # Replace fake nulls with NaN
        df[col] = df[col].replace(fake_nulls, np.nan)
 
# Optional: Summary of NaNs per column
print("\nNaN count per column:")
print(df.isna().sum())
 
# Show final cleaned DataFrame
print("\nCleaned DataFrame:")
print(df)

Rows where 'exemption_value' has fake nulls:
         exemption_value
55                   NaN
58                   NaN
60                   NaN
61                   NaN
63                   NaN
...                  ...
45356821             NaN
45356822             NaN
45356823             NaN
45356824             NaN
45356825             NaN

[16762044 rows x 1 columns]
Rows where 'rate_2023' has fake nulls:
          rate_2023
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
45356821        NaN
45356822        NaN
45356823        NaN
45356824        NaN
45356825        NaN

[30516317 rows x 1 columns]
Rows where 'rate_2025' has fake nulls:
          rate_2025
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
45356709        NaN
45356710        NaN
45356727        NaN
45356728        NaN
45356729        NaN

[30508737 rows x 1 columns]
Rows where 'rate_2026' has fake nulls:
          rate_2026
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
45356821        NaN
45356822        NaN
45356823        NaN
45356824        NaN
45356825        NaN

[45356826 rows x 1 columns]
Rows where 'rate_2024' has fake nulls:
          rate_2024
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
45356821        NaN
45356822        NaN
45356823        NaN
45356824        NaN
45356825        NaN

[30508981 rows x 1 columns]
Rows where 'rate_2022' has fake nulls:
          rate_2022
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
45356821        NaN
45356822        NaN
45356823        NaN
45356824        NaN
45356825        NaN

[30519242 rows x 1 columns]
Rows where 'rate_2020' has fake nulls:
          rate_2020
8               NaN
9               NaN
10              NaN
11              NaN
12              NaN
...             ...
45356821        NaN
45356822        NaN
45356823        NaN
45356824        NaN
45356825        NaN

[37939837 rows x 1 columns]
Rows where 'rate_2021' has fake nulls:
          rate_2021
16              NaN
17              NaN
18              NaN
19              NaN
20              NaN
...             ...
45356821        NaN
45356822        NaN
45356823        NaN
45356824        NaN
45356825        NaN

[30517424 rows x 1 columns]

NaN count per column:
parcel                    0
exemption_value    16762044
rate_2023          30516317
arb_status                0
jurisdiction              0
rate_2025          30508737
rate_2026          45356826
rate_2024          30508981
year                      0
rate_2022          30519242
rate_2020          37939837
rate_2021          30517424
district                  0
page_save                 0
dtype: int64

Cleaned DataFrame:
                 parcel exemption_value  rate_2023             arb_status  \
0         1166790050010          38,042        NaN  Certified: 08/06/2021
1         1166790050010          52,166        NaN  Certified: 08/06/2021
2         1166790050010          52,166        NaN  Certified: 08/06/2021
3         1166790050010          52,166        NaN  Certified: 08/06/2021
4         1166790050010          52,166        NaN  Certified: 08/06/2021
...                 ...             ...        ...                    ...
45356821  0451750020001             NaN        NaN          Not Certified
45356822  0451750020001             NaN        NaN          Not Certified
45356823  0451750020001             NaN        NaN          Not Certified
45356824  0451750020001             NaN        NaN          Not Certified
45356825  0451750020001             NaN        NaN          Not Certified

                    jurisdiction  rate_2025  rate_2026  rate_2024  year  \
0                CLEAR CREEK ISD        NaN        NaN        NaN  2021
1                  HARRIS COUNTY        NaN        NaN        NaN  2021
2          HARRIS CO FLOOD CNTRL        NaN        NaN        NaN  2021
3          PORT OF HOUSTON AUTHY        NaN        NaN        NaN  2021
4            HARRIS CO HOSP DIST        NaN        NaN        NaN  2021
...                          ...        ...        ...        ...   ...
45356821   PORT OF HOUSTON AUTHY   0.005900        NaN        NaN  2026
45356822     HARRIS CO HOSP DIST   0.187610        NaN        NaN  2026
45356823     HARRIS CO EDUC DEPT   0.004798        NaN        NaN  2026
45356824         CITY OF HOUSTON   0.519190        NaN        NaN  2026
45356825  SPRING BRANCH MGT DIST   0.100000        NaN        NaN  2026

          rate_2022  rate_2020  rate_2021 district                page_save
0               NaN    1.26590    1.17970      027  1166790050010_2021.html
1               NaN    0.39116    0.37693      040  1166790050010_2021.html
2               NaN    0.03142    0.03349      041  1166790050010_2021.html
3               NaN    0.00991    0.00872      042  1166790050010_2021.html
4               NaN    0.16671    0.16221      043  1166790050010_2021.html
...             ...        ...        ...      ...                      ...
45356821        NaN        NaN        NaN      042  0451750020001_2026.html
45356822        NaN        NaN        NaN      043  0451750020001_2026.html
45356823        NaN        NaN        NaN      044  0451750020001_2026.html
45356824        NaN        NaN        NaN      061  0451750020001_2026.html
45356825        NaN        NaN        NaN      793  0451750020001_2026.html

[45356826 rows x 14 columns]

In [8]:
df[df['parcel'] == 1166790050010]

Empty DataFrame
Columns: [parcel, exemption_value, rate_2023, arb_status, jurisdiction, rate_2025, rate_2026, rate_2024, year, rate_2022, rate_2020, rate_2021, district, page_save]
Index: []

In [9]:
df[df['parcel'] == 451750020001]

Empty DataFrame
Columns: [parcel, exemption_value, rate_2023, arb_status, jurisdiction, rate_2025, rate_2026, rate_2024, year, rate_2022, rate_2020, rate_2021, district, page_save]
Index: []

In [10]:
df['exemption_value'].value_counts()

exemption_value
0            2065630
Pending       464321
5,000         363244
100,000       255089
50,000        200974
              ...
2,795,000          1
789,572            1
490,054            1
545,054            1
542,660            1
Name: count, Length: 583208, dtype: int64

In [11]:
df[df['exemption_value'] == 'Pending']

,parcel,exemption_value,rate_2023,arb_status,jurisdiction,rate_2025,rate_2026,rate_2024,year,rate_2022,rate_2020,rate_2021,district,page_save
426,0270450800017,Pending,NaN,Pending,HOUSTON ISD,0.878300,NaN,NaN,2026,NaN,NaN,NaN,001,0270450800017_2026.html
428,0270450800017,Pending,NaN,Pending,HARRIS COUNTY,0.380960,NaN,NaN,2026,NaN,NaN,NaN,040,0270450800017_2026.html
429,0270450800017,Pending,NaN,Pending,HARRIS CO FLOOD CNTRL,0.049660,NaN,NaN,2026,NaN,NaN,NaN,041,0270450800017_2026.html
430,0270450800017,Pending,NaN,Pending,PORT OF HOUSTON AUTHY,0.005900,NaN,NaN,2026,NaN,NaN,NaN,042,0270450800017_2026.html
431,0270450800017,Pending,NaN,Pending,HARRIS CO HOSP DIST,0.187610,NaN,NaN,2026,NaN,NaN,NaN,043,0270450800017_2026.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45355106,0730310020012,Pending,NaN,Pending,HARRIS CO HOSP DIST,0.187610,NaN,NaN,2026,NaN,NaN,NaN,043,0730310020012_2026.html
45355108,0730310020012,Pending,NaN,Pending,HARRIS CO EDUC DEPT,0.004798,NaN,NaN,2026,NaN,NaN,NaN,044,0730310020012_2026.html
45355109,0730310020012,Pending,NaN,Pending,CROSBY MUD,0.280000,NaN,NaN,2026,NaN,NaN,NaN,146,0730310020012_2026.html
45355111,0730310020012,Pending,NaN,Pending,HC EMERG SRV DIST 80,0.046106,NaN,NaN,2026,NaN,NaN,NaN,669,0730310020012_2026.html
45355113,0730310020012,Pending,NaN,Pending,HC EMERG SRV DIST 5,0.030000,NaN,NaN,2026,NaN,NaN,NaN,675,0730310020012_2026.html

In [12]:
cols = ['exemption_value']
df[cols] = df[cols].replace('Pending', np.nan)

In [13]:
df['exemption_value'] = df['exemption_value'].replace({r',':''}, regex=True).astype('Int64')

In [14]:
(df == 0).sum()

parcel                   0
exemption_value    2065630
rate_2023            15037
arb_status               0
jurisdiction             0
rate_2025             8858
rate_2026                0
rate_2024            14963
year                     0
rate_2022            10547
rate_2020             5693
rate_2021            10565
district                 0
page_save                0
dtype: Int64

In [15]:
df[df['rate_2020'] == 0]

,parcel,exemption_value,rate_2023,arb_status,jurisdiction,rate_2025,rate_2026,rate_2024,year,rate_2022,rate_2020,rate_2021,district,page_save
27358,1124120000804,0,NaN,Certified: 08/06/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,1124120000804_2021.html
27971,1124060000642,0,NaN,Certified: 08/06/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,1124060000642_2021.html
38007,1281520231353,0,NaN,Certified: 08/06/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,1281520231353_2021.html
41243,1281520231340,0,NaN,Certified: 08/06/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,1281520231340_2021.html
69326,1281520241380,0,NaN,Certified: 08/06/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,1281520241380_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45302965,0984130000906,0,NaN,Certified: 08/06/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,0984130000906_2021.html
45303539,0650760000019,0,NaN,Supplemental: 09/10/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,0650760000019_2021.html
45303557,0984130000904,0,NaN,Correction: 01/13/2023,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,0984130000904_2021.html
45310470,0791230030067,<NA>,NaN,Supplemental: 10/01/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,0791230030067_2021.html
45310751,0791230030065,<NA>,NaN,Certified: 08/06/2021,SUNBELT FWSD,NaN,NaN,NaN,2021,NaN,0.0,0.0,838,0791230030065_2021.html

In [16]:
cool = ['exemption_value', 'rate_2023', 'rate_2020', 'rate_2021', 'rate_2022', 'rate_2024', 'rate_2025']
df[cool] = df[cool].replace(0, np.nan)

In [17]:
df

,parcel,exemption_value,rate_2023,arb_status,jurisdiction,rate_2025,rate_2026,rate_2024,year,rate_2022,rate_2020,rate_2021,district,page_save
0,1166790050010,38042,NaN,Certified: 08/06/2021,CLEAR CREEK ISD,NaN,NaN,NaN,2021,NaN,1.26590,1.17970,027,1166790050010_2021.html
1,1166790050010,52166,NaN,Certified: 08/06/2021,HARRIS COUNTY,NaN,NaN,NaN,2021,NaN,0.39116,0.37693,040,1166790050010_2021.html
2,1166790050010,52166,NaN,Certified: 08/06/2021,HARRIS CO FLOOD CNTRL,NaN,NaN,NaN,2021,NaN,0.03142,0.03349,041,1166790050010_2021.html
3,1166790050010,52166,NaN,Certified: 08/06/2021,PORT OF HOUSTON AUTHY,NaN,NaN,NaN,2021,NaN,0.00991,0.00872,042,1166790050010_2021.html
4,1166790050010,52166,NaN,Certified: 08/06/2021,HARRIS CO HOSP DIST,NaN,NaN,NaN,2021,NaN,0.16671,0.16221,043,1166790050010_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45356821,0451750020001,<NA>,NaN,Not Certified,PORT OF HOUSTON AUTHY,0.005900,NaN,NaN,2026,NaN,NaN,NaN,042,0451750020001_2026.html
45356822,0451750020001,<NA>,NaN,Not Certified,HARRIS CO HOSP DIST,0.187610,NaN,NaN,2026,NaN,NaN,NaN,043,0451750020001_2026.html
45356823,0451750020001,<NA>,NaN,Not Certified,HARRIS CO EDUC DEPT,0.004798,NaN,NaN,2026,NaN,NaN,NaN,044,0451750020001_2026.html
45356824,0451750020001,<NA>,NaN,Not Certified,CITY OF HOUSTON,0.519190,NaN,NaN,2026,NaN,NaN,NaN,061,0451750020001_2026.html
45356825,0451750020001,<NA>,NaN,Not Certified,SPRING BRANCH MGT DIST,0.100000,NaN,NaN,2026,NaN,NaN,NaN,793,0451750020001_2026.html

In [18]:
coll = ['rate_2023', 'rate_2020', 'rate_2021', 'rate_2022', 'rate_2024', 'rate_2025']
df[coll] = df[coll].astype(float)

In [19]:
df

,parcel,exemption_value,rate_2023,arb_status,jurisdiction,rate_2025,rate_2026,rate_2024,year,rate_2022,rate_2020,rate_2021,district,page_save
0,1166790050010,38042,NaN,Certified: 08/06/2021,CLEAR CREEK ISD,NaN,NaN,NaN,2021,NaN,1.26590,1.17970,027,1166790050010_2021.html
1,1166790050010,52166,NaN,Certified: 08/06/2021,HARRIS COUNTY,NaN,NaN,NaN,2021,NaN,0.39116,0.37693,040,1166790050010_2021.html
2,1166790050010,52166,NaN,Certified: 08/06/2021,HARRIS CO FLOOD CNTRL,NaN,NaN,NaN,2021,NaN,0.03142,0.03349,041,1166790050010_2021.html
3,1166790050010,52166,NaN,Certified: 08/06/2021,PORT OF HOUSTON AUTHY,NaN,NaN,NaN,2021,NaN,0.00991,0.00872,042,1166790050010_2021.html
4,1166790050010,52166,NaN,Certified: 08/06/2021,HARRIS CO HOSP DIST,NaN,NaN,NaN,2021,NaN,0.16671,0.16221,043,1166790050010_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45356821,0451750020001,<NA>,NaN,Not Certified,PORT OF HOUSTON AUTHY,0.005900,NaN,NaN,2026,NaN,NaN,NaN,042,0451750020001_2026.html
45356822,0451750020001,<NA>,NaN,Not Certified,HARRIS CO HOSP DIST,0.187610,NaN,NaN,2026,NaN,NaN,NaN,043,0451750020001_2026.html
45356823,0451750020001,<NA>,NaN,Not Certified,HARRIS CO EDUC DEPT,0.004798,NaN,NaN,2026,NaN,NaN,NaN,044,0451750020001_2026.html
45356824,0451750020001,<NA>,NaN,Not Certified,CITY OF HOUSTON,0.519190,NaN,NaN,2026,NaN,NaN,NaN,061,0451750020001_2026.html
45356825,0451750020001,<NA>,NaN,Not Certified,SPRING BRANCH MGT DIST,0.100000,NaN,NaN,2026,NaN,NaN,NaN,793,0451750020001_2026.html

In [20]:
(df == 'UNKNOWN').sum()

parcel             0
exemption_value    0
rate_2023          0
arb_status         0
jurisdiction       0
rate_2025          0
rate_2026          0
rate_2024          0
year               0
rate_2022          0
rate_2020          0
rate_2021          0
district           0
page_save          0
dtype: Int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45356826 entries, 0 to 45356825
Data columns (total 14 columns):
 #   Column           Dtype
---  ------           -----
 0   parcel           object
 1   exemption_value  Int64
 2   rate_2023        float64
 3   arb_status       object
 4   jurisdiction     object
 5   rate_2025        float64
 6   rate_2026        float64
 7   rate_2024        float64
 8   year             int64
 9   rate_2022        float64
 10  rate_2020        float64
 11  rate_2021        float64
 12  district         object
 13  page_save        object
dtypes: Int64(1), float64(7), int64(1), object(5)
memory usage: 4.8+ GB

In [22]:
df.columns

Index(['parcel', 'exemption_value', 'rate_2023', 'arb_status', 'jurisdiction',
       'rate_2025', 'rate_2026', 'rate_2024', 'year', 'rate_2022', 'rate_2020',
       'rate_2021', 'district', 'page_save'],
      dtype='object')

In [23]:
df = df.reindex(columns=['parcel', 'year', 'district','jurisdiction', 'exemption_value','arb_status','rate_2020','rate_2021','rate_2022', 'rate_2023', 'rate_2024', 
       'rate_2025', 'rate_2026', 
        'page_save']
       )

In [24]:
df

,parcel,year,district,jurisdiction,exemption_value,arb_status,rate_2020,rate_2021,rate_2022,rate_2023,rate_2024,rate_2025,rate_2026,page_save
0,1166790050010,2021,027,CLEAR CREEK ISD,38042,Certified: 08/06/2021,1.26590,1.17970,NaN,NaN,NaN,NaN,NaN,1166790050010_2021.html
1,1166790050010,2021,040,HARRIS COUNTY,52166,Certified: 08/06/2021,0.39116,0.37693,NaN,NaN,NaN,NaN,NaN,1166790050010_2021.html
2,1166790050010,2021,041,HARRIS CO FLOOD CNTRL,52166,Certified: 08/06/2021,0.03142,0.03349,NaN,NaN,NaN,NaN,NaN,1166790050010_2021.html
3,1166790050010,2021,042,PORT OF HOUSTON AUTHY,52166,Certified: 08/06/2021,0.00991,0.00872,NaN,NaN,NaN,NaN,NaN,1166790050010_2021.html
4,1166790050010,2021,043,HARRIS CO HOSP DIST,52166,Certified: 08/06/2021,0.16671,0.16221,NaN,NaN,NaN,NaN,NaN,1166790050010_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45356821,0451750020001,2026,042,PORT OF HOUSTON AUTHY,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.005900,NaN,0451750020001_2026.html
45356822,0451750020001,2026,043,HARRIS CO HOSP DIST,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.187610,NaN,0451750020001_2026.html
45356823,0451750020001,2026,044,HARRIS CO EDUC DEPT,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.004798,NaN,0451750020001_2026.html
45356824,0451750020001,2026,061,CITY OF HOUSTON,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.519190,NaN,0451750020001_2026.html
45356825,0451750020001,2026,793,SPRING BRANCH MGT DIST,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.100000,NaN,0451750020001_2026.html

In [25]:
checks = {
    "Numeric 0": 0,
    "String '0'": "0",
    "Hyphen '-'": "-",
    "Dot '.'": ".",
    "Comma ','": ",",
    "Backtick '`'": "`",
    "Star '*'": "*",
    "Dollar '$'": "$",
    "Percent '%'": "%",
    "Underscore '_'": "_",
    "Hashtag '#'": "#",
    "At '@'": "@",
    "Exclamation '!'": "!",
    "Question '?'": "?",
    "Colon ':'": ":",
    "Semicolon ';'": ";",
    "Slash '/'": "/",
    "Backslash '\\'": "\\",
    "Pipe '|'": "|",
    "Plus '+'": "+",
    "Equals '='": "=",
    "Caret '^'": "^",
    "Tilde '~'": "~",
    "Open Paren '('": "(",
    "Close Paren ')'": ")",  
    "Open Bracket '['": "[",
    "Close Bracket ']'": "]",
    "Open Brace '{'": "{",
    "Close Brace '}'": "}",
}

for label, val in checks.items():
    print(f"\n=== {label} ===")
    result = (df == val).sum().loc[lambda x: x > 0]
    print(result.to_string() if not result.empty else "No matches found")

=== Numeric 0 ===
No matches found

=== String '0' ===
No matches found

=== Hyphen '-' ===
No matches found

=== Dot '.' ===
No matches found

=== Comma ',' ===
No matches found

=== Backtick '`' ===
No matches found

=== Star '*' ===
No matches found

=== Dollar '$' ===
No matches found

=== Percent '%' ===
No matches found

=== Underscore '_' ===
No matches found

=== Hashtag '#' ===
No matches found

=== At '@' ===
No matches found

=== Exclamation '!' ===
No matches found

=== Question '?' ===
No matches found

=== Colon ':' ===
No matches found

=== Semicolon ';' ===
No matches found

=== Slash '/' ===
No matches found

=== Backslash '\' ===
No matches found

=== Pipe '|' ===
No matches found

=== Plus '+' ===
No matches found

=== Equals '=' ===
No matches found

=== Caret '^' ===
No matches found

=== Tilde '~' ===
No matches found

=== Open Paren '(' ===
No matches found

=== Close Paren ')' ===
No matches found

=== Open Bracket '[' ===
No matches found

=== Close Bracket ']' ===
No matches found

=== Open Brace '{' ===
No matches found

=== Close Brace '}' ===
No matches found

In [26]:
cols = df.columns.difference(['parcel', 'page_save'])
 
mask = df[cols].isna().all(axis=1)
df[mask]

Empty DataFrame
Columns: [parcel, year, district, jurisdiction, exemption_value, arb_status, rate_2020, rate_2021, rate_2022, rate_2023, rate_2024, rate_2025, rate_2026, page_save]
Index: []

In [27]:
df[df.duplicated()]

Empty DataFrame
Columns: [parcel, year, district, jurisdiction, exemption_value, arb_status, rate_2020, rate_2021, rate_2022, rate_2023, rate_2024, rate_2025, rate_2026, page_save]
Index: []

In [28]:
df[df['parcel'] == 270450800017]

Empty DataFrame
Columns: [parcel, year, district, jurisdiction, exemption_value, arb_status, rate_2020, rate_2021, rate_2022, rate_2023, rate_2024, rate_2025, rate_2026, page_save]
Index: []

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45356826 entries, 0 to 45356825
Data columns (total 14 columns):
 #   Column           Dtype
---  ------           -----
 0   parcel           object
 1   year             int64
 2   district         object
 3   jurisdiction     object
 4   exemption_value  Int64
 5   arb_status       object
 6   rate_2020        float64
 7   rate_2021        float64
 8   rate_2022        float64
 9   rate_2023        float64
 10  rate_2024        float64
 11  rate_2025        float64
 12  rate_2026        float64
 13  page_save        object
dtypes: Int64(1), float64(7), int64(1), object(5)
memory usage: 4.8+ GB

In [30]:
df.drop(columns={'rate_2026'}, inplace=True)

In [31]:
df.to_csv(r"D:\Texas\Harris\Property\Cleaned_Data\us_tx_48201_data_prop_exemption-jurisdictions_silver_20260501.csv", index=False)
df

,parcel,year,district,jurisdiction,exemption_value,arb_status,rate_2020,rate_2021,rate_2022,rate_2023,rate_2024,rate_2025,page_save
0,1166790050010,2021,027,CLEAR CREEK ISD,38042,Certified: 08/06/2021,1.26590,1.17970,NaN,NaN,NaN,NaN,1166790050010_2021.html
1,1166790050010,2021,040,HARRIS COUNTY,52166,Certified: 08/06/2021,0.39116,0.37693,NaN,NaN,NaN,NaN,1166790050010_2021.html
2,1166790050010,2021,041,HARRIS CO FLOOD CNTRL,52166,Certified: 08/06/2021,0.03142,0.03349,NaN,NaN,NaN,NaN,1166790050010_2021.html
3,1166790050010,2021,042,PORT OF HOUSTON AUTHY,52166,Certified: 08/06/2021,0.00991,0.00872,NaN,NaN,NaN,NaN,1166790050010_2021.html
4,1166790050010,2021,043,HARRIS CO HOSP DIST,52166,Certified: 08/06/2021,0.16671,0.16221,NaN,NaN,NaN,NaN,1166790050010_2021.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45356821,0451750020001,2026,042,PORT OF HOUSTON AUTHY,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.005900,0451750020001_2026.html
45356822,0451750020001,2026,043,HARRIS CO HOSP DIST,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.187610,0451750020001_2026.html
45356823,0451750020001,2026,044,HARRIS CO EDUC DEPT,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.004798,0451750020001_2026.html
45356824,0451750020001,2026,061,CITY OF HOUSTON,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.519190,0451750020001_2026.html
45356825,0451750020001,2026,793,SPRING BRANCH MGT DIST,<NA>,Not Certified,NaN,NaN,NaN,NaN,NaN,0.100000,0451750020001_2026.html